<?php
namespace GroupMeApiClient;

class EmojiUtils {
    const PLACEHOLDER = "☃";
    
    private function __construct() {}
    
    public static function getEmojiSequenceByName($name) {
        if (isset(self::$emojis[$name])) {
            return self::$emojis[$name];
        }
    }
    
    public static function getEmojiNameBySequence(array $sequence) {
        foreach (self::$emojis as $name => $seq) {
            if ($seq == $sequence) {
                return $name;
            }
        }
    }
    
    public static function getEmojiNameByPackAndIndex($pack, $index) {
        $sequence = array($pack, $index);
        return self::getEmojiNameBySequence($sequence);
    }
    
    public static function getCharmapFromEmojiNames(array $names) {
        $callback = 'self::getEmojiSequenceByName';
        return array_map($callback, $names);
    }
    
    public static function extractEmojiNamesFromText($text) {
        $charmap = array();
        
        if (preg_match_all('~(:[A-Za-z0-9_\-!]+:)~', $text, $matches)) {
            foreach ($matches[1] as $m) {
                $seq = self::getEmojiSequenceByName($m);
                if (!$seq) continue;

                $charmap[] = $seq;
                $text = preg_replace("~$m~", self::PLACEHOLDER, $text, 1);
            }
        }
        
        return array(
            'text' => $text,
            'charmap' => $charmap,
        );
    }
    
    public static function injectEmojiNamesIntoText($text, $charmap) {
        $placeholder=self::PLACEHOLDER;
        //$text = str_replace(chr(194).chr(160), ' ', $text);
        
        foreach ($charmap as $seq) {
            $name = self::getEmojiNameBySequence($seq);
            $text = preg_replace("~$placeholder~", $name, $text, 1);
        }
        
        return $text;
    }
    
    private static $emojis = array(
        ':smiley_face:' => array(1, 0),
        ':happy_face:' => array(1, 1),
        ':pleased_face:' => array(1, 2),
        ':content_face:' => array(1, 3),
        ':winky_face:' => array(1, 4),
        ':thrilled_face:' => array(1, 5),
        ':swoon_face:' => array(1, 6),
        ':clown_face:' => array(1, 7),
        ':goofy_face:' => array(1, 8),
        ':silly_face:' => array(1, 9),
        ':neil_face:' => array(1, 10),
        ':glasses_face:' => array(1, 11),
        ':cool_guy_face:' => array(1, 12),
        ':cigar_face:' => array(1, 13),
        ':blank_face:' => array(1, 14),
        ':bummed_face:' => array(1, 15),
        ':sad_face:' => array(1, 16),
        ':tearful_face:' => array(1, 17),
        ':crying_face:' => array(1, 18),
        ':nervous_face:' => array(1, 19),
        ':frustrated_face:' => array(1, 20),
        ':mad_face:' => array(1, 21),
        ':conniving_face:' => array(1, 22),
        ':grossed_out_face:' => array(1, 23),
        ':sick_face:' => array(1, 24),
        ':puking_face:' => array(1, 25),
        ':dead_face:' => array(1, 26),
        ':yawn_face:' => array(1, 27),
        ':surprised_face:' => array(1, 28),
        ':shocked_face:' => array(1, 29),
        ':stoney_face:' => array(1, 30),
        ':tweak_face:' => array(1, 31),
        ':kissy_face:' => array(1, 32),
        ':surprised_glasses_face:' => array(1, 33),
        ':hand_over_mouth_face:' => array(1, 34),
        ':hands_over_eyes_face:' => array(1, 35),
        ':confused_face:' => array(1, 36),
        ':zipper_mouth_face:' => array(1, 37),
        ':sleeping_face:' => array(1, 38),
        ':caffeinated_face:' => array(1, 39),
        ':emo_face:' => array(1, 40),
        ':gasp_face:' => array(1, 41),
        ':goatee_face:' => array(1, 42),
        ':steve:' => array(1, 43),
        ':jared:' => array(1, 44),
        ':iced_coffee:' => array(1, 45),
        ':latte:' => array(1, 46),
        ':icecream_cookie:' => array(1, 47),
        ':hotsauce:' => array(1, 48),
        ':tacotaco:' => array(1, 49),
        ':pizza:' => array(1, 50),
        ':popping_bottle:' => array(1, 51),
        ':brown_bottle:' => array(1, 52),
        ':lighter:' => array(1, 53),
        ':red_solo_cup:' => array(1, 54),
        ':pingpong:' => array(1, 55),
        ':pinball_flipper:' => array(1, 56),
        ':pink_electric_guitar:' => array(1, 57),
        ':wet_wipes:' => array(1, 58),
        ':dead_fish:' => array(1, 59),
        ':petey:' => array(1, 60),
        ':pivotal:' => array(1, 61),
        ':dino:' => array(1, 62),
        ':heart:' => array(1, 63),
        ':badge_icon:' => array(1, 64),
        ':grilled_cheese:' => array(1, 65),
        ':poundie:' => array(1, 66),
        ':frowndie:' => array(1, 67),
        ':headphones_poundie:' => array(1, 68),
        ':blonde_poundie:' => array(1, 69),
        ':nerdie_poundie:' => array(1, 70),
        ':evil_poundie:' => array(1, 71),
        ':angel_poundie:' => array(1, 72),
        ':kitty_poundie:' => array(1, 73),
        ':pink_bow_poundie:' => array(1, 74),
        ':3d_poundie:' => array(1, 75),
        ':sunglasses_poundie:' => array(1, 76),
        ':beanie_poundie:' => array(1, 77),
        ':bowtie_poundie:' => array(1, 78),
        ':kissie_poundie:' => array(1, 79),
        ':bandit_poundie:' => array(1, 80),
        ':disguise_poundie:' => array(1, 81),
        ':beard_poundie:' => array(1, 82),
        ':tongue_out_poundie:' => array(1, 83),
        ':backwards_hat_smiley_face:' => array(2, 0),
        ':snorkel_face:' => array(2, 1),
        ':sporty_sun_glasses_face:' => array(2, 2),
        ':life_vest_face:' => array(2, 3),
        ':watermelon_mouth_face:' => array(2, 4),
        ':taking_a_picture_face:' => array(2, 5),
        ':shutter_shades_face:' => array(2, 6),
        ':face_with_speedo:' => array(2, 7),
        ':thong_butt:' => array(2, 8),
        ':dreadlocks:' => array(2, 9),
        ':sunscreen:' => array(2, 10),
        ':tanning:' => array(2, 11),
        ':paradise:' => array(2, 12),
        ':sunset:' => array(2, 13),
        ':fireworks:' => array(2, 14),
        ':beachball:' => array(2, 15),
        ':flippers:' => array(2, 16),
        ':sun:' => array(2, 17),
        ':sun_with_sunglasses:' => array(2, 18),
        ':kite:' => array(2, 19),
        ':surfing_doggie:' => array(2, 20),
        ':life_saver:' => array(2, 21),
        ':sail_boat:' => array(2, 22),
        ':hawaiian_shirt:' => array(2, 23),
        ':board_shorts:' => array(2, 24),
        ':bikini:' => array(2, 25),
        ':flip_flops:' => array(2, 26),
        ':sun_tan_lotion:' => array(2, 27),
        ':aviator_glasses:' => array(2, 28),
        ':sun_hat:' => array(2, 29),
        ':sand_castle:' => array(2, 30),
        ':sand_bucket:' => array(2, 31),
        ':sea_shell:' => array(2, 32),
        ':water_gun:' => array(2, 33),
        ':air_conditioner:' => array(2, 34),
        ':fan:' => array(2, 35),
        ':fire_hyrdrant:' => array(2, 36),
        ':ice_bag:' => array(2, 37),
        ':popsicle:' => array(2, 38),
        ':baseball:' => array(2, 39),
        ':pit-stained_shirt:' => array(2, 40),
        ':jorts:' => array(2, 41),
        ':bee:' => array(2, 42),
        ':spilled_ice_cream:' => array(2, 43),
        ':deal_with_it_dog:' => array(2, 44),
        ':car_trip:' => array(2, 45),
        ':camp_fire:' => array(2, 46),
        ':marshmallow:' => array(2, 47),
        ':graham_cracker:' => array(2, 48),
        ':chocolate_bar:' => array(2, 49),
        ':mosquito:' => array(2, 50),
        ':grill:' => array(2, 51),
        ':grilled_steak:' => array(2, 52),
        ':grilled_chicken:' => array(2, 53),
        ':hotdog:' => array(2, 54),
        ':hamburger:' => array(2, 55),
        ':can:' => array(2, 56),
        ':fish_taco:' => array(2, 57),
        ':bacon:' => array(2, 58),
        ':lettuce:' => array(2, 59),
        ':tomato:' => array(2, 60),
        ':pickle:' => array(2, 61),
        ':avocado:' => array(2, 62),
        ':peach:' => array(2, 63),
        ':blueberry:' => array(2, 64),
        ':raspberry:' => array(2, 65),
        ':strawberry:' => array(2, 66),
        ':banana:' => array(2, 67),
        ':watermelon:' => array(2, 68),
        ':blender:' => array(2, 69),
        ':margarita:' => array(2, 70),
        ':pina_colada:' => array(2, 71),
        ':drink_umbrella:' => array(2, 72),
        ':slice_of_lime:' => array(2, 73),
        ':coconut_drink:' => array(2, 74),
        ':lemonade:' => array(2, 75),
        ':ice_cream_cone:' => array(2, 76),
        ':ice_cream_sandwich:' => array(2, 77),
        ':shark:' => array(2, 78),
        ':gold_fish:' => array(2, 79),
        ':squid:' => array(2, 80),
        ':starfish:' => array(2, 81),
        ':crab:' => array(2, 82),
        ':lobster:' => array(2, 83),
        ':sting_ray:' => array(2, 84),
        ':stack_of_books_face:' => array(3, 0),
        ':taped_glasses_face:' => array(3, 1),
        ':writing_face:' => array(3, 2),
        ':open_laptop:' => array(3, 3),
        ':science_experiment:' => array(3, 4),
        ':painter:' => array(3, 5),
        ':backpack_front:' => array(3, 6),
        ':backpack_back:' => array(3, 7),
        ':singer:' => array(3, 8),
        ':wrestler:' => array(3, 9),
        ':football_player:' => array(3, 10),
        ':#1_fan:' => array(3, 11),
        ':marching_band_leader:' => array(3, 12),
        ':cheerleader:' => array(3, 13),
        ':sleep_deprived_face:' => array(3, 14),
        ':stressed_out_face:' => array(3, 15),
        ':graduate:' => array(3, 16),
        ':prom_king:' => array(3, 17),
        ':prom_queen:' => array(3, 18),
        ':toga:' => array(3, 19),
        ':upside-down_face:' => array(3, 20),
        ':lamp_shade_head:' => array(3, 21),
        ':school_bus:' => array(3, 22),
        ':A+:' => array(3, 23),
        ':Fail:' => array(3, 24),
        ':spiral_notebook:' => array(3, 25),
        ':#2_pencil:' => array(3, 26),
        ':paper_airplane:' => array(3, 27),
        ':calculator:' => array(3, 28),
        ':globe:' => array(3, 29),
        ':chalk_board:' => array(3, 30),
        ':bell:' => array(3, 31),
        ':diploma:' => array(3, 32),
        ':teachers_pet:' => array(3, 33),
        ':sack_lunch:' => array(3, 34),
        ':school_lunch:' => array(3, 35),
        ':varsity_jacket:' => array(3, 36),
        ':fencing:' => array(3, 37),
        ':lacrosse:' => array(3, 38),
        ':field_hockey:' => array(3, 39),
        ':cleat:' => array(3, 40),
        ':soccer_ball:' => array(3, 41),
        ':basketball:' => array(3, 42),
        ':baseball_hit:' => array(3, 43),
        ':football:' => array(3, 44),
        ':hockey:' => array(3, 45),
        ':frisbee:' => array(3, 46),
        ':stadium:' => array(3, 47),
        ':drama_club:' => array(3, 48),
        ':bicycle:' => array(3, 49),
        ':pool_table:' => array(3, 50),
        ':bunk_bed:' => array(3, 51),
        ':laundry:' => array(3, 52),
        ':alarm_clock:' => array(3, 53),
        ':lava_lamp:' => array(3, 54),
        ':guitar:' => array(3, 55),
        ':video_game_controller:' => array(3, 56),
        ':BRB:' => array(3, 57),
        ':shower_shoes:' => array(3, 58),
        ':shower_caddy:' => array(3, 59),
        ':prescription:' => array(3, 60),
        ':freshman_15:' => array(3, 61),
        ':condom:' => array(3, 62),
        ':sweatpants:' => array(3, 63),
        ':sweatpants_behind:' => array(3, 64),
        ':hippy_sandals:' => array(3, 65),
        ':pot_of_coffee:' => array(3, 66),
        ':ramen:' => array(3, 67),
        ':mac_and_cheese:' => array(3, 68),
        ':takeout:' => array(3, 69),
        ':pizza_box:' => array(3, 70),
        ':chips:' => array(3, 71),
        ':energy_drink:' => array(3, 72),
        ':real_ID:' => array(3, 73),
        ':cups:' => array(3, 74),
        ':pony:' => array(3, 75),
        ':shot_glass:' => array(3, 76),
        ':alpha:' => array(3, 77),
        ':beta:' => array(3, 78),
        ':gamma:' => array(3, 79),
        ':delta:' => array(3, 80),
        ':epsilon:' => array(3, 81),
        ':zeta:' => array(3, 82),
        ':eta:' => array(3, 83),
        ':theta:' => array(3, 84),
        ':iota:' => array(3, 85),
        ':kappa:' => array(3, 86),
        ':lambda:' => array(3, 87),
        ':mu:' => array(3, 88),
        ':nu:' => array(3, 89),
        ':xi:' => array(3, 90),
        ':omicron:' => array(3, 91),
        ':pi:' => array(3, 92),
        ':rho:' => array(3, 93),
        ':sigma:' => array(3, 94),
        ':tau:' => array(3, 95),
        ':upsilon:' => array(3, 96),
        ':phi:' => array(3, 97),
        ':chi:' => array(3, 98),
        ':psi:' => array(3, 99),
        ':omega:' => array(3, 100),
        ':pirate:' => array(4, 0),
        ':witch:' => array(4, 1),
        ':ghost:' => array(4, 2),
        ':vampire:' => array(4, 3),
        ':scary_nurse:' => array(4, 4),
        ':red_riding_hood:' => array(4, 5),
        ':cowboy:' => array(4, 6),
        ':jason_mask:' => array(4, 7),
        ':mummy:' => array(4, 8),
        ':frankenstein:' => array(4, 9),
        ':bride_of_frankenstein:' => array(4, 10),
        ':zombie:' => array(4, 11),
        ':ax_head:' => array(4, 12),
        ':policeman:' => array(4, 13),
        ':lion:' => array(4, 14),
        ':werewolf:' => array(4, 15),
        ':scream_mask:' => array(4, 16),
        ':fairy_princess:' => array(4, 17),
        ':hot_dog_dog:' => array(4, 18),
        ':jack_o_lantern:' => array(4, 19),
        ':spider_web:' => array(4, 20),
        ':skull:' => array(4, 21),
        ':grim_reaper:' => array(4, 22),
        ':boo!:' => array(4, 23),
        ':coffin:' => array(4, 24),
        ':bloody_hand:' => array(4, 25),
        ':spider:' => array(4, 26),
        ':bat:' => array(4, 27),
        ':cauldron:' => array(4, 28),
        ':trick_or_treat!:' => array(4, 29),
        ':candy_corn:' => array(4, 30),
        ':smashed_pumpkin:' => array(4, 31),
        ':eggs:' => array(4, 32),
        ':tp_tree:' => array(4, 33),
        ':black_cat:' => array(4, 34),
        ':flying_witch:' => array(4, 35),
        ':rip:' => array(4, 36),
        ':pilgrim:' => array(5, 0),
        ':native_american:' => array(5, 1),
        ':leaf_pile:' => array(5, 2),
        ':chef:' => array(5, 3),
        ':about_to_eat:' => array(5, 4),
        ':so_full:' => array(5, 5),
        ':food_coma:' => array(5, 6),
        ':black_friday_shopper:' => array(5, 7),
        ':watching_the_game:' => array(5, 8),
        ':cornucopia:' => array(5, 9),
        ':maize:' => array(5, 10),
        ':hand_turkey:' => array(5, 11),
        ':living_turkey:' => array(5, 12),
        ':baster:' => array(5, 13),
        ':deal_with_it_turkey:' => array(5, 14),
        ':gravy:' => array(5, 15),
        ':mashed_potatoes:' => array(5, 16),
        ':stuffing:' => array(5, 17),
        ':cranberry_sauce:' => array(5, 18),
        ':sweet_potatoes_and_marshmallows:' => array(5, 19),
        ':green_beans:' => array(5, 20),
        ':rolls:' => array(5, 21),
        ':dog_begging:' => array(5, 22),
        ':full_plate:' => array(5, 23),
        ':empty_plate:' => array(5, 24),
        ':wish_bone:' => array(5, 25),
        ':pumpkin_pie:' => array(5, 26),
        ':hot_apple_cider:' => array(5, 27),
        ':wine:' => array(5, 28),
        ':leftover_sandwich:' => array(5, 29),
        ':dreidel:' => array(5, 30),
        ':menorah:' => array(5, 31),
        ':gelt:' => array(5, 32),
        ':jelly_donut:' => array(5, 33),
        ':santa:' => array(10, 0),
        ':mrs_claus:' => array(10, 1),
        ':elf:' => array(10, 2),
        ':caroler:' => array(10, 3),
        ':mistletoe_kiss:' => array(10, 4),
        ':keviiiiin:' => array(10, 5),
        ':bundled_up:' => array(10, 6),
        ':snowing:' => array(10, 7),
        ':snowflake_on_tongue:' => array(10, 8),
        ':hit_with_snowball:' => array(10, 9),
        ':skier:' => array(10, 10),
        ':sick:' => array(10, 11),
        ':christmas_tree_car:' => array(10, 12),
        ':christmas_tree:' => array(10, 13),
        ':sad_christmas_tree:' => array(10, 14),
        ':present:' => array(10, 15),
        ':santa_hat:' => array(10, 16),
        ':christmas_lights:' => array(10, 17),
        ':wreath:' => array(10, 18),
        ':ornament:' => array(10, 19),
        ':mistletoe:' => array(10, 20),
        ':stocking:' => array(10, 21),
        ':fireplace:' => array(10, 22),
        ':gingerbread_man:' => array(10, 23),
        ':candy_cane:' => array(10, 24),
        ':milk_and_cookies:' => array(10, 25),
        ':hot_chocolate:' => array(10, 26),
        ':ugly_sweater:' => array(10, 27),
        ':party_dress:' => array(10, 28),
        ':sleigh:' => array(10, 29),
        ':snow_globe:' => array(10, 30),
        ':rudolph:' => array(10, 31),
        ':penguin:' => array(10, 32),
        ':dog_with_antlers:' => array(10, 33),
        ':snowman:' => array(10, 34),
        ':ice_skate:' => array(10, 35),
        ':snowflake:' => array(10, 36),
        ':2014_glasses:' => array(10, 37),
        ':noisemaker:' => array(10, 38),
        ':nye_kiss:' => array(10, 39),
        ':cheers:' => array(10, 40),
        ':midnight:' => array(10, 41),
    );
}
